# Generated by Django 6.1.1 on 2026-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='source',
            field=models.CharField(choices=[('NUCLEAR', 'Nucléaire'), ('WIND', 'Éolien'), ('BIOENERGY', 'Bioénergie'), ('FOSSIL_GAS', 'Gaz fossile'), ('FOSSIL_OIL', 'Fioul'), ('FOSSIL_HARD_COAL', 'Charbon'), ('HYDRO', 'Hydraulique'), ('SOLAR', 'Solaire'), ('EXCHANGE', 'Échange'), ('PUMPING', 'Pompage')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('recorded_at', 'source'), name='unique_reading_per_time_and_source'),
        ),
    ]
