services:
  db:
    image:  postgres:16
    environment:
      POSTGRES_DB:  gridinsight
      POSTGRES_USER:  gridinsight
      POSTGRES_PASSWORD:  gridinsight
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: